# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Before Your Trip',  url: 'before'}
- {name: 'Destinations',      url: 'destinations'}
- {name: 'About',              url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:  'mailto:info.travel2china@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
#pagination:
#  next_page: 'Newer'
#  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

post_date_prefix: 'Update on'
